sudo: false

language: generic

cache:
  directories:
  - $HOME/.stack

before_install:
- mkdir -p ~/.local/bin
- export PATH=$HOME/.local/bin:$PATH
- travis_retry curl -L https://www.stackage.org/stack/linux-x86_64 | tar xz --wildcards --strip-components=1 -C ~/.local/bin '*/stack'

install:
- stack install

script:
- make clean
- stack exec site rebuild

deploy:
  - provider: s3
    access_key_id: "$AWS_ACCESS"
    secret_access_key: "$AWS_SECRET"
    bucket: "blog.notadomain.com"
    region: eu-central-1
    skip_cleanup: true
    acl: public_read
    local_dir: _site
    on:
      branch: master
  - provider: pages
    github_token: $GITHUB_TOKEN
    repo: mo-gr/mo-gr.github.com
    target_branch: master
    skip_cleanup: true
    acl: public_read
    local_dir: _site
    on:
      branch: master
